[project]
name = "llm-finetune-supportbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.10.1",
    "bitsandbytes>=0.47.0",
    "datasets>=4.0.0",
    "peft>=0.17.1",
    "transformers>=4.55.4",
]
